@startuml

class NBodySimulator {
-step: float
-step_num: int
-t: float
+NBodySimulator(universe: Universe, windowSize: int)
+animate(): void
-draw_body(): void
}

class Universe {
-radius: float
-numBodies: int
+Universe(name: string): Universe
+forces_acting_upon(body: Body) -> np.array
+from_file(filename: string): Universe
}

class Body {
{static} G: float
-position : np.array
-velocity : np.array
-mass : float
+Body(m : float, pos : float[2], vel : float[2]) : Body
-distance(a: float, b: float): float
+force_from(self: Body, other: Body): np.array
+update(self: Body, total_force: np.array, step: float): void
}

note bottom of NBodySimulator: "universe és un atribut implicit del tipus Universe"
note bottom of Universe: "bodies és un atribut implicit del tipus Body[numBodies]"

Universe "   1" -left-* NBodySimulator: universe
Body "1..*" -left-* Universe: bodies

@enduml