@startuml

class NBodySimulator {
-step: float
-step_num: int
+NBodySimulator(universe: Universe, windowSize: int)
}

class Universe {
-radius: float
-numBodies: int
+Universe(name: string): Universe
+from_file(filename: string): Universe
}

class Body {
{static} G: float
-position : np.array
-velocity : np.array
-mass : float
+Body(m : float, pos : float[2], vel : float[2]) : Body
}

note bottom of NBodySimulator: "universe és un atribut implicit del tipus Universe"
note bottom of Universe: "bodies és un atribut implicit del tipus Body[numBodies]"

Universe "   1" -left-* NBodySimulator: universe
Body "1..*" -left-* Universe: bodies

@enduml