@startuml
class RandomForestClassifier {
+MAX_DEPTH
+fit()
-make_decision_trees()
-make_node()
-make_leaf()
-make_parent_or_leaf()
-best_split()
-CART_cost()
-gini()
}

interface Node {
{abstract} +predict(x : list(float)) : int
}

class Leaf {
+predict(x : list(float)) : int
}

class Parent {
+predict(x : list(float)) : int
}

class Dataset {
+ {static}X
+ {static}y
+ {static}num_samples
+ {static}num_features

+ most_frequent_label()
+split()
}

RandomForestClassifier *-right-> "1..*" Node : decision_trees
Leaf -up--|> Node
Parent -up--|> Node
Parent ---> Node : left_child
Parent ---> Node : right_child
RandomForestClassifier .down. Dataset

@enduml